Necrobot-Private/NecroBot

- PoGo.NecroBot.GUI/PoGo.NecroBot.GUI.csproj
Targeting ```AnyCPU``` causes GUI project to not build at all since Awesomium browser is x86 only.  ```PlatformTarget``` needs to be set to ```x86```.
> Fix GUI build - Awesomium browser only supports x86 builds

- PoGo.NecroBot.Logic/Service/Elevation/BaseElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/ElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/GoogleElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/MapQuestElevationService.cs
Added alert when Google Elevation API isn't working.
Also fixes bug where altitudes like -32000m were allowed and used.
It is said that the (real) client isn't sending altitudes (atm). Still might as well have these parts working.
> Fixes elevation-related issues

- PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
- PoGo.NecroBot.Logic/Model/Google/GoogleWalk.cs
- PoGo.NecroBot.Logic/Model/Mapzen/MapzenWalk.cs
- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/MapzenWalkConfig.cs
- PoGo.NecroBot.Logic/Navigation.cs
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Service/GoogleDirectionsService.cs
- PoGo.NecroBot.Logic/Service/MapzenDirectionsService.cs
- PoGo.NecroBot.Logic/Strategies/Walk/BaseWalkStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/FlyStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/GoogleStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/HumanPathWalkingStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/HumanStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/IWalkStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/MapzenNavigationStrategy.cs
- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
Navigation enhancements:
1) Better error handling and fallback - You should NEVER get a Google error again, even if you run out of requests for the day.
2) Blacklist for failing navigation strategies - It now has a priority queue that it goes through to find the next best strategy. If a strategy fails, it will be blacklisted for the next hour.  This is a performance fix also since previously it would keep hitting the failed service over and over, slowing down the bot.
Google -> Mapzen -> Yours -> Default Walking
3) Added Mapzen navigation strategy.  This is probably the best strategy since it has no daily limits once you have obtained a key, it looks pretty human, and it is fast and stable.
The human navigation strategies we support now are:
1) Google (requires a key)
2) Mapzen (requires …
> Navigation enhancements - Mapzen strategy added

- PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/GoogleWalkConfig.cs
- PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/MapzenWalkConfig.cs
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Service/Elevation/BaseElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/ElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/IElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/MapQuestElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/MapzenElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/RandomElevationService.cs
1) Added mapzen elevation service
2) Cleaned up the error handling and logic for elevation services.  If an elevation service returns a negative elevation, a very clear warning is shown, and then we fallback to the next service.
Priorities are:
Mapzen -> MapQuest -> Google -> Random (random elevation between 5 and 50)
Why this order?
1. Mapzen is fast and reliable once you get an API key. No daily limits
2. MapQuest does not require a key and for most users returns a good elevation value.
3. Google is last because I think using it for elevation uses up your quota for Google Directions API.
> Elevation enhancements - Add mapzen elevation service

- PoGo.NecroBot.CLI/Program.cs
Allows you to override kill switch.  If kill switch is active, it will prompt you if you want to override.
Bot at your own risk!
> Add killswitch override prompt.  Now you can override killswitch. 

- PoGo.NecroBot.CLI/ConsoleLogger.cs
- PoGo.NecroBot.CLI/Program.cs
- PoGo.NecroBot.CLI/WebSocketInterface.cs
- PoGo.NecroBot.Logic/Logging/ILogger.cs
- PoGo.NecroBot.Logic/Logging/Logger.cs
- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/State/VersionCheckState.cs
- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
- PoGo.NecroBot.Logic/Utils/ErrorHandler.cs
Bug fix for GUI missing some of the initial console log messages that were sent before the GUI connected to the bot.
Changes:
1. Replace all `Console.WriteLine` with `Logger.Write` to make sure messages go to both console and GUI console.
2. Add log buffering for console logger - Console is written to immediately but the messages are also buffered and output when the GUI has connected to the bot via websocket.
> Bug fix - Buffer console log until gui is loaded.

- PoGo.NecroBot.Logic/Strategies/Walk/BaseWalkStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/FlyStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/HumanPathWalkingStrategy.cs
- PoGo.NecroBot.Logic/Strategies/Walk/HumanStrategy.cs
- PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
- PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
- PoGo.NecroBot.Logic/Utils/LocationUtils.cs
Update to Rocket API for better iOS emulation. 
- Speed is now passed into the API (required for iOS) when player location is updated.
- If speed of 0 is passed in, then a random speed is used.
> Better iOS emulation

- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
Bug fix - Bot was skipping pokestops if you did not have Google walk enabled or you had YoursWalk enabled.
Fixes #184
> Bug fix for bot skipping pokestops

- PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
- PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
- PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Fixes the problems with WildPokemon etc not working with Incense/Lures.
Ugly/untidy version. In a hurry so will have to clean up the code later. Seemingly works though. Second opinion welcome!
> Fix #179 WildPokemon-error with Incense/Lures

- PoGo.NecroBot.Logic/Model/IGeoLocation.cs
Poke stop location names were no longer being shown. This adds the poke stop name back to the FortLocation object so that it is shown in the console again.
> Bug fix - Console not showing poke stop name.

- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
Fixes pokestop spin bug.  Skip poke stop when the cooldown is in the future.
#213
> Fix pokestop spin bug (bug #213)

- PoGo.NecroBot.CLI/Program.cs
- PoGo.NecroBot.Logic/Model/Settings/ClientSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/Service/Elevation/BaseElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/ElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/GoogleElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/IElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/MapQuestElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/MapzenElevationService.cs
- PoGo.NecroBot.Logic/Service/Elevation/RandomElevationService.cs
- PoGo.NecroBot.Logic/State/Session.cs
- PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs
- PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
- PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs
- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
- PoGo.NecroBot.Logic/Utils/LocationUtils.cs
- Elevation services needs to be created before session is created in order for settings to be able to access elevation service.
- Elevation services now no longer need session but instead simply require the `GlobalSettings` object in order to look up the API keys from settings.
#232
> Bug fix - Fix #232 - Default altitude not set from elevation service.

- PoGo.NecroBot.Logic/Model/Settings/CatchConfig.cs
- PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
This is a ban precaution. 
- Regional pokemon should be added by default to ```PokemonsToIgnore``` list.
- `UsePokemonToNotCatchFilter` set to true by default.
- `UsePokemonSniperFilterOnly` set to true by default.
#244
> Bug fix #244 - By default add regional pokemon to PokemonsToIgnore list

- PoGo.NecroBot.Logic/Model/IGeoLocation.cs
When walking back to GPX coordinates, there is no name for the location.  So we need to check for null `fortInfo` before using it.  
#251
> Fix bug #251 - Check for null before setting location name.

- PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
- PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
Cleans up the MSniperServiceTask to re-use the same `CatchPokemonTask` logic that is used elsewhere when catching pokemon.  A lot of the code duplication is now gone.
@msx752 Please take a look and make sure everything looks good.
Testing with changes seems to be working:
#202
> Fix bug #202 - MSniper sniped pokemon should count against limits.

- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
When we hit the pokestop limit, bot ends up walking back and forth between 2 pokestops.  This fixes the behavior of the bot so that it continues to walk more than 2 pokestops.
This is related to #215.  Now you can set 
```
"PokeStopLimit": 0,
```
and it will continue to walk and catch pokemon while skipping pokestops.
Fixes bug #215
> Fix bug #215 - Continue to walk pokestops when hit pokestop limit

- PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
When use NecroBot with "subPath" parameter for multi bot and use MSniper to catch Pokemons.
1. MSniper write the "SnipeMS.json" file for NecroBot use to catch Pokemons in the current directory of Necrobot.
2. NecroBot check "SnipeMS.json" file to catch Pokemons from session.LogicSettings.ProfilePath (current directory + subPath).
> Fix MSnipe don't work when use subpath parameter.

- PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
- PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
This reverts changes made in commit 9b2460c219fde1bc6f0da1b17c1a6ed47833d268, which changed `DelayBetweenPokemonCatch` to `DelayBetweenPokemonUpgrade` unintentionally.
The delay between pokemon catches and snipes was using the wrong delay value `DelayBetweenPokemonUpgrade` instead of `DelayBetweenPokemonCatch`.  This means that it would wait up to 10 seconds between catches/snipes if using the default upgrade delay.
> Catching/Sniping pokemon not respecting DelayBetweenPokemonCatch setting.

- PoGo.NecroBot.Logic/Inventory.cs
- PoGo.NecroBot.Logic/PoGoUtils/PokemonInfo.cs
- PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs
1. After upgrading pokemon, the cached inventory is not refreshed, which may result in stale data causing error.  Now we refresh cached inventory after each upgrade.
1. Added more error handling for null values.
Fixes #243
> Fixes bug #243 - Fix error while upgrading pokemon

- PoGo.NecroBot.CLI/BotDataSocketClient.cs
- PoGo.NecroBot.CLI/Program.cs
- PoGo.NecroBot.Logic/State/VersionCheckState.cs
- PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
We have now 2 types of kill switches:
1) Automatic kill switch - if Nia ever forces an update and our API emulation version becomes incompatible, then bot will automatically detect this and stop.
2) Manual kill switch - if we detect something that Nia is doing (i.e. captcha stuff) that may cause bans, we may enable manual kill switch to protect your accounts.
> Re-enable manual kill switch

- PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
- Change default settings to allow pokemon to be sniped by default.
- By default set `UsePokemonToNotCatchFilter` to true, so that we don't snipe the regional pokemon by default (ban safety).
Recommended default config now is:
```
"PokemonsToIgnore": [
"tauros",
"mrmime",
"kangaskhan",
"farfetchd"
],
```
And
```
"UsePokemonToNotCatchFilter": true,
"UsePokemonSniperFilterOnly": false,
```
This allows all pokemon to be caught by default, except for the regional pokemon.  Advanced users can customize the snipe list and enable the snipe filter by setting `UsePokemonSniperFilterOnly` to true.
#298 
#299 
#302
> Fixes #298 - Don't skip pokemon by default.

- PoGo.NecroBot.Logic/Inventory.cs
When program start, it often get empty inventory information. Add retry to reget it.
It also add protection and retry in get pokemon settings to prevent crash.
> Add retry when getInventory empty

- PoGo.NecroBot.CLI/Program.cs
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Service/TelegramService.cs
- PoGo.NecroBot.Logic/State/LoadSaveState.cs
- PoGo.NecroBot.Logic/State/Session.cs
- PoGo.NecroBot.Logic/State/SessionStats.cs
- PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
- PoGo.NecroBot.Logic/app.config
- PoGo.NecroBot.Logic/packages.config
Fixes the pokestop/pokemon limit bug which occurs when a relog happens - the pokestop/pokemon limits are saved twice.
- We are now storing all session stats in an embedded database called LiteDB.  
- The session stats are in a file called SessionStats.db. PokemonTS.txt and PokestopTS.txt data will be imported into the database and then deleted.
- The database is self-cleaning. It will automatically clean out data that is older than 24 hours.
Fixes #336
> Re-work pokestop and pokemon limits to store session stats in LiteDB

- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
- PoGo.NecroBot.Logic/State/VersionCheckState.cs
Re-designed the configuration update mechanism to properly upgrade config file.
1. Config files now have a schema version associated with them, which is used to determine when an upgrade of the config is needed.
2. Before an update occurs, the old config.json is backed up to `config-<old version>.backup.json`, so you should never lose your old settings, and you can compare the old and the new.
3. Updates to your configuration file now happen whenever you start up the bot.  The bot will check to see if your configuration is outdated and will upgrade properly.
4. The update mechanism is able to handle upgrades for multiple versions.  For example, if you are using schema version 1 and the newest version is 8, then the update mechanism will upgrade from 1->2, 2->3, 3->4, etc. until the config …
> Fix the update mechanism to properly upgrade old config file.

- PoGo.NecroBot.Logic/State/Session.cs
default logedtime set to min value then cause 1 st account only be run 1 and never be switched.
> fix wrong run time for first account

- PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
- PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
Old Setting Was Causing All Possible Evolutions To Be Done If Your Bag Was Fuller Than Specified Amount And Max Interger Was 350 So If Someone Had 1000 Bag Size And Carried 400 Pokemon After Every Action It Would Cause Your Pokemon To Evolve
> EvolveKeptPokemonsOverrideStartIfThisManyReady Should Be EvolveKeptPokemonIfBagHasOverThisManyPokemon

- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Service/TelegramCommand/AccountsCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/AllCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/CommandLocation.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/CommandMessage.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/ExitCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/HelpCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/ICommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/ICommandGenerify.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/ItemsCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/LocCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/LogsCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/PokedexCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/ProfileCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/RecycleCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/RestartCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/SnipeCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/StatusCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/TopCommand.cs
- PoGo.NecroBot.Logic/Service/TelegramService.cs
- PoGo.NecroBot.Logic/Service/TelegramUtils.cs
I wondered that the /loc telegram command was not listed when using the /help command. (And why my german translation (merged a few days ago) for the help message is not localized).
I refactored TelegramService.cs a bit, added an further interface, added some abstract classes bringing default implementations for common Telegram callbacks, modified the current interface and adapted all classes inherting from it... Further information are in the commit message.
Now you have a much better microframework to invoke any kind of (typed) callback - the /loc command is listed properly and i prepared to fix the missing localization of 'Telegram Bot' messages.
> Refactors TelegramService.cs

- PoGo.NecroBot.Logic/Common/UITranslation.cs
- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
- PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
- PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs
- PoGo.Necrobot.Window/Controls/PokemonInventory.xaml
Rename token now changed to {Name}_{IV}_{Level} so they can change order or rename by level since many of them want to rename pokemon by level
> Allow rename by level token

- PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs
Resuming the attack when the final duel lost or elapsed time to fight but won at least one battle.
As a result, if we are not able to overcome all at once oprońców after defeating at least one wzawiamy fight instead of going to the next Gym. Zdywanie Gyms this process becomes more efficient and faster.
> Resuming the attack

- PoGo.NecroBot.CLI/ConsoleEventListener.cs
- PoGo.NecroBot.Logic/Event/RenamePokemonEvent.cs
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs
- PoGo.NecroBot.Logic/Tasks/RenameSinglePokemonTask.cs
- PoGo.Necrobot.Window/MainClientWindow.xaml.UIEvents.cs
- PoGo.Necrobot.Window/Model/PokemonDataViewModel.cs
- PoGo.Necrobot.Window/Model/PokemonListModel.cs
Allows you to rename pokemon from the WPF GUI.
Fixes #742
> Add ability to rename pokemon from WPF GUI

- PoGo.NecroBot.Logic/Common/UITranslation.cs
- PoGo.Necrobot.Window/Controls/PokemonInventory.xaml
- PoGo.Necrobot.Window/Model/PokemonDataViewModel.cs
- PoGo.Necrobot.Window/Model/PokemonListModel.cs
- PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
- PoGo.Necrobot.Window/packages.config
Display capture location in WPF GUI pokemon inventory.
I'm using a LRU cache to decrease the number of reverse geocoding HTTP calls that we make.  Fortunately the grid view is also smart and only lazily reverse geocodes the items in view, so performance is not too bad.
We can store capture locations in database on the disk if performance is unacceptable.
One more thought @samuraitruong, I have a suspicion that the geo-coding code should not belong in the `PokemonDataViewModel`, but was not sure where the best place is with MVVM.
Fixes #755
> Add caught location to pokemon inventory

- PoGo.Necrobot.Window/Model/PokemonListModel.cs
Fix duplicate pokemon in WPF GUI inventory after evolve.
Fixes bug #774
> Fix bug #774 - Duplicate pokemon in WPF GUI inventory after evolve.

- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
Fix migration from version 10 to 11 of schema
Fixes #781
> Fix bug #781 - DefaultBuddyPokemon should be set to empty string

- PoGo.NecroBot.Logic/Event/FortUsedEvent.cs
- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
- PoGo.Necrobot.Window/Controls/MapControl.xaml.cs
- PoGo.Necrobot.Window/Controls/MapMarkers/FortMarker.xaml.cs
- PoGo.Necrobot.Window/MainClientWindow.xaml.UIEvents.cs
- PoGo.Necrobot.Window/Model/FortViewModel.cs
Pokestops change color when spun, but never reset back to initial state in the WPF map.
This is only a fix for pokestops.  The issue with map pokemon not disappearing when they expire is still not fixed yet.
Fix bug #790
> Fix bug #790 - Pokestops should change back to the unvisited color when spinnable

- PoGo.NecroBot.Logic/Inventory.cs
Should allow a level 30 snorlax to upgrade to level 32 if i am trainer level 30.
Fixes bug #812
> Bug fix #812 - Allow pokemon to be upgraded to more than 2 levels greater than trainer level

- PoGo.NecroBot.Logic/Service/Elevation/ElevationService.cs
Mapzen and Google elevation should be disabled if UseMapzenWalk or UseGoogleWalk are turned off.
Fixes #832
> Fixes bug #832 - Mapzen and Google elevation services sometimes incorrectly enabled

- PoGo.Necrobot.Window/Model/FortViewModel.cs
The map is not reflecting the correct state of pokestops. When a pokestop is spun, it still looks like it is not spun in the WPF GUI map.
Fixes bug #835
> Fix pokestop status not updating on WPF map.

- PoGo.NecroBot.Logic/Model/GeoLocation.cs
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Utils/AsyncLock.cs
- PoGo.NecroBot.Logic/packages.config
- PoGo.Necrobot.Window/Model/PokemonDataViewModel.cs
- PoGo.Necrobot.Window/Model/PokemonListModel.cs
Add reverse geolocation database to speed up lookup of pokemon caught locations.
New geolocation database is a LiteDB file found in Cache\geolocations.db and is shared by all bots when multibotting.
Fixes #815 
Fixes #826
> Add reverse geolocation caching to speed up WPF GUI pokemon inventory

- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
More tweaks to help with softbans when spinning pokestops.
Fixes bug #860
> More tweaks to fix pokestop out of range bug.

- PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
When catching pokemon, occasionally you will get out of range error. This makes sure that you are always in range before encounter.
> Bug fix - Encounter out of range bug

- PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/HumanlikeDelays.cs
- PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
This implements https://github.com/Necrobot-Private/NecroBot/issues/732. Added new configuration section HumanlikeDelays, where you can tweak pokemon catching closer to actual client as described in issue.
It is unclear to me that should this get some sort of schema migration or should this be added to schema.
> (Enchanment) Delays for catch (Issue-732)

- PoGo.NecroBot.Logic/State/LoadSaveState.cs
Add additional safety check to not save our last position if outside the max travel distance.
Fixes bug #1027
> Fix bug #1027 - Don't save last position to file if it is greater than MaxTravelDistanceInMeters

- PoGo.Necrobot.Window/MainClientWindow.xaml
- Changes Font Size on Tabs from 15 to 14
- Decrease Height on player info by 30 pixels to make room for "Eggs" Tab
Before:
After:
> Support for 1366x768 Resolutions

- PoGo.NecroBot.Logic/Inventory.cs
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Tasks/BaseTransferPokemonTask.cs
- PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs
- PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs
- PoGo.NecroBot.Logic/Tasks/TransferWeakPokemonTask.cs
If KeepPokemonsThatCanEvolve is true and TransferWeakPokemon is true, there is a bug where weak transfer will ignore the favorited pokemon and pokemon in the PokemonsNotToTransfer list.
TransferWeakPokemon also did not respect the PokemonTransferFilters.
Fixes #1077
> Fix bug #1077 - Fix TransferWeakPokemon transferring favorited pokemon and pokemon in PokemonsNotToTransfer

- PoGo.Necrobot.Window/Model/SnipeListViewModel.cs
This is a bug fix for inventory updates, which were occasionally not working properly, causing random errors (trying to use berries when you don't have any, trying to evolve pokemon that are already transfered, incomplete pokedex, etc.)
Also, fixed a bug with Not In Pokedex snipe list in the WPF GUI, which should be updated everytime the inventory is updated.
Fixes #1081
Fixes #1076
Fixes #1108
> Bug fix/inventory

- PoGo.NecroBot.Logic/State/CatchState.cs
- PoGo.NecroBot.Logic/State/FarmState.cs
- PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/HumanRandomActionTask.cs
- PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs
- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
Evolutions not running if transfers are disabled.
Fixes #1104
> Fixes #1104 - Evolutions and transfers should not be coupled together

- PoGo.NecroBot.Logic/MultiAccountManager.cs
Fixes bug with accounts.db migration which is causing issues on startup when accounts.db does not exist.
Fixes #1115
> Bug fix/accounts db upgrade

- PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
During unverified snipe, we may potentially get out of range error during encounter if the coordinates are not precise enough. This may fix that problem.
Fixes #1136
> Fix potential encounter out of range during snipe.

- PoGo.NecroBot.Logic/Utils/Statistics.cs
- PoGo.Necrobot.Window/Model/PlayerInfoModel.cs
Changes the xp display to be only for the current level instead of total experience.
Fixes #1133
> Update xp display to be just for current level instead of total.

- PoGo.NecroBot.CLI/Properties/AssemblyInfo.cs
- PoGo.NecroBot.GUI/Properties/AssemblyInfo.cs
- PoGo.NecroBot.Logic/Properties/AssemblyInfo.cs
> Push 133Update

- PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/CatchSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs
This Way People Can Turn On And Off A List Of Pokemon They Want To Catch Locally But They Can Still Snipe The Pokemon That They Want Or AutoSnipe Pokemon That Meet There Snipe Requirements Much More Efficient Than Using PokemonToIgnore List And Can Be Easily Turned On And Off. Closes #1153 Request. Please Double Check But Worked GREAT Locally
> Pokemon To Catch Locally List

- PoGo.Necrobot.Window/FilterSetting.xaml
- PoGo.Necrobot.Window/MainClientWindow.xaml
- PoGo.Necrobot.Window/PokedexWindow.xaml
- PoGo.Necrobot.Window/SettingsWindow.xaml
- PoGo.Necrobot.Window/SplashScreen.xaml
Description:
This PR Fixes Titles so that they Match the Bot's Font as well as are not caps anymore, LIKE THIS.
It also adds a few fixes to the Code to better organize it
Files Edited:
* PokedexWindow.xaml
* SplashScreen.xaml
* SettingsWindow.xaml
* FilterSetting.xaml
* MainWindow.xaml
Happy Botting, 
CDA 👍
> [Asthetics] Code Organization Fixes + Titles No Longer Caps

- PoGo.NecroBot.CLI/Forms/StarterConfigForm.cs
- PoGo.NecroBot.CLI/Program.cs
- PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/AuthSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/ClientSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/MultipleBotConfig.cs
- PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
- PoGo.NecroBot.Logic/MultiAccountManager.cs
- PoGo.NecroBot.Logic/Service/TelegramCommand/AccountsCommand.cs
- PoGo.NecroBot.Logic/State/Session.cs
- PoGo.NecroBot.Logic/State/StateMachine.cs
- PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
- PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
Big clean up of multibot functionality:
1) Clean up auth.json.  There is now only one `Bots` section which contains all authentication info. The old `AuthConfig` in auth.json is now removed.
2) Multibot is always enabled now. So there is no need for `AllowMultipleBot` in auth.json.
Fixes #1161
> Big clean up of multi bot functionality. Multibot is now always enabled.

- PoGo.Necrobot.Window/Model/AddManualSnipeCoordViewModel.cs
Coordinates were parsed depending on your locale settings, but it should be parsed independent of your locale settings.
Fixed bug #1312
> Fixes bug #1312 - Manual snipe coords not parsed properly occasionally

- PoGo.NecroBot.Logic/State/VersionCheckState.cs
Fixing auto updater for bintray:
1) We now need to use versioned zip files (instead of NecroBot.Console.zip it is now NecroBot.Console.1.0.0.141.zip).
2) Downloads should come from BinTray and not Github.
> Fix auto updater to download versioned zip from BinTray.

- PoGo.NecroBot.CLI/Properties/AssemblyInfo.cs
- PoGo.NecroBot.Logic/Properties/AssemblyInfo.cs
- PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
This PR fixes a few typos as well as changing the PostBuild command to copy From the actual PokeEase Submodule rather than the electron gui version, resulting in a more updated pokeease
> Minor Text Fixes + Edits to PostBuild Command

- PoGo.NecroBot.Logic/Model/ElevationLocation.cs
- PoGo.NecroBot.Logic/Model/GeoLocation.cs
- PoGo.NecroBot.Logic/MultiAccountManager.cs
- PoGo.NecroBot.Logic/State/SessionStats.cs
v152 introduced a bug in loading the 4 litedb databases that we use for storing data. We need to migrate the databases in order to be able to load them again.
Fixes #1442
> Fixes #1442 - Upgrade all LiteDB 3.0 databases.

- PoGo.NecroBot.CLI/Program.cs
- PoGo.NecroBot.Logic/Inventory.cs
- PoGo.NecroBot.Logic/Model/Settings/AuthConfig.cs
- PoGo.NecroBot.Logic/Model/Settings/AuthSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/MultiAccountManager.cs
- PoGo.NecroBot.Logic/State/LoginState.cs
- PoGo.NecroBot.Logic/State/Session.cs
- PoGo.Necrobot.Window/Converters/DurationTextConverter.cs
Fixes the runtime total for the bot to be accurate now.  There is a change in the behavior of this now in that we now reset the runtime totals when the bot is started..  Since this runtime total was previously never reset, nor was there a way to manually reset the value (except deleting the database file), the best compromise was to just reset it when the bot starts up.
Fixes #1392 
Fixes #1451
> Fix runtime totals when multibotting

- PoGo.NecroBot.Logic/MultiAccountManager.cs
When runtime is equal (i.e. 0 on first startup), we should sort accounts by their ID.
Fixes #1477
> Fix ordering of bot runtime when runtime total is equal.

- PoGo.NecroBot.Logic/Model/Settings/AuthSettings.cs
When setting auth.json DevicePackageName to "random" device is
generated, but sets android-related values to "" instead of null.  Fix
sets the five values to null on random device generation.
Wasn't able to set these in call to generate the device.  Tested, and properly sets Android device information to null instead of "".
Error was during auth.json verification:
[20:28:18] () Validating Auth.json...
[20:28:18] () auth.json [Line: 21, Position: 26]: DeviceConfig.AndroidBoardName String '' does not match regex pattern '[a-zA-Z0-9_\-\.\s]'.
[20:28:18] () auth.json [Line: 22, Position: 27]: DeviceConfig.AndroidBootloader String '' does not match regex pattern '[a-zA-Z0-9_\-\.\s]'.
[20:28:18] () auth.json [Line: 25, Position: 31]: DeviceConfig.DeviceModelIdentifier String '' does not match …
> Fix Android device variables when generating random iOS device.

- PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
- PoGo.NecroBot.Logic/Model/Settings/PokeStopConfig.cs
- PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
- PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
Looks like Niantic has added new limits for number of pokemon caught and pokestops spun. The limits are now dynamically changing according to the data that we have. Based on users in the PogoDev forum, here's how it seems to work:
New accounts have limits of 2100 pokestops and 1500 pokemon before you get softbanned.
If exceed half of the limit (e.g. around 750), then the next day the limits seem to be decreased to 500.
And then if you hit the limit again that day, then the limits are decreased to 200 or 300 the following day.
This pull sets the limits per day to 500 pokemons and 700 pokestops to avoid getting softbanned.
Fixes #1558
> Decrease softban limits (500 pokemon, 700 pokestops)

- PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
- PoGo.NecroBot.CLI/packages.config
- PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
- PoGo.NecroBot.Logic/packages.config
- PoGo.Necrobot.Window/MainClientWindow.xaml
- PoGo.Necrobot.Window/MainClientWindow.xaml.cs
- PoGo.Necrobot.Window/Model/DataContext.cs
- PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
- PoGo.Necrobot.Window/packages.config
- RocketBot2/RocketBot2.csproj
- RocketBot2/packages.config
Google.Protobuf & Google.Protobuf.Tools - v3.2.0 to v3.3.0
Microsoft.ASPNET.SignalR.Client - v2.2.1 to v2.2.2
Fody - v2.0.6 to v2.0.7
Signed-off-by: CDAGaming
PRs:
- [FeroxRev/RocketAPI](https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/117)
- [POGOProtos](https://github.com/Necrobot-Private/POGOProtos/pull/35)
> Updates Dependencies (Necrobot + RocketBot)

- PoGo.NecroBot.Logic/MultiAccountManager.cs
When migrating or loading data from LiteDB to SQLite, we should check for empty username and password to avoid causing error.
> Add empty checks for username and password when importing auth info.

- PoGo.Necrobot.Window/MainClientWindow.xaml.cs
This pull generates a log file for DotNetBrowser in the Logs directory when running a debug build.
@hardknoxni69a This is to help in debugging your issue.
> Enable DotNetBrowser debug logging when running debug build.

- PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs
- PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
We need to fix gym battle logic to move on to the next pokestop/gym when gym is unattackable.
Fixes #1662
> Fix gym battle to properly move on if gym is unattackable.

- PoGo.NecroBot.Logic/TinyIoC.cs
This PR Realigns TinyIoC.cs to Master and Includes several Bug-Fix PR Changes:
Included PRs:
https://github.com/grumpydev/TinyIoC/pull/114
https://github.com/grumpydev/TinyIoC/pull/111
https://github.com/grumpydev/TinyIoC/pull/110
https://github.com/grumpydev/TinyIoC/pull/105
> Updates TinyIoC.cs

- PoGo.NecroBot.Logic/Model/Settings/SnipeConfig.cs
- PoGo.NecroBot.Logic/Service/BotDataSocketClient.cs
- PoGo.NecroBot.Logic/State/BotSwitcherState.cs
- PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
- PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Sniping is back!  This pull implements short range sniping (auto sniping works as well as manual sniping from the Win.GUI sniper).  Here's how it works:
1) We are still feeding our bots with data from our sniping server.  However, only pokemon within a small range will be processed and added to the sniping lists.  This range is configurable (see below).
2) There are 2 movement options for sniping: a) Teleporting, and b) Walking.  
3) Teleporting MAY result in catch flee when encountering the pokemon.  This seems to be dependent on how far the jump is. Teleporting may also not be that much faster - you may notice a long pause (up to 30 seconds) after the jump. This is due to the bot refreshing the map and waiting for the teleport softban to expire.
4) Walking is always reliable but …
> Bug fix/local sniping

- PoGo.Necrobot.Window/MainClientWindow.xaml
- PoGo.Necrobot.Window/MainClientWindow.xaml.cs
This PR Adds Support for Specific Colors for Light,Dark, and Default. It also sets the ConsoleThemer Border to a Default Color to match the bar itself
> Fix ConsoleThemer Border & Add 3-Way Color Support (WIP)

- PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
- PoGo.NecroBot.CLI/packages.config
- PoGo.NecroBot.Logic/Common/UITranslation.cs
- PoGo.Necrobot.Window/App.xaml.cs
- PoGo.Necrobot.Window/Controls/MapControl.xaml
- PoGo.Necrobot.Window/Controls/PlayerInfo.xaml
- PoGo.Necrobot.Window/Controls/PokemonInventory.xaml
- PoGo.Necrobot.Window/Controls/PokemonInventory.xaml.cs
- PoGo.Necrobot.Window/Controls/SnipeGrid.xaml
- PoGo.Necrobot.Window/Controls/SniperControl.xaml
- PoGo.Necrobot.Window/MainClientWindow.xaml
- PoGo.Necrobot.Window/MainClientWindow.xaml.UIEvents.cs
- PoGo.Necrobot.Window/MainClientWindow.xaml.cs
- PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
- PoGo.Necrobot.Window/packages.config
- RocketBot2/RocketBot2.csproj
- RocketBot2/packages.config
- Fix for Console Colors Calling Incorrectly
- Fix for Console Missing Light-Scheme Colors
- Fix for Console Starting, Regardless of User Settings
- Fixes for Incorrect Font Calling
- Theme, Scheme, and Map Mode Foregrounds now have their Correct Settings
- App Now Saves and Loads Width and Height of Application Correctly
- Tab Backgrounds are now Their Correct Color (Transparent, for now)
- Fixes Circumstance in which if you cancel Bulk Transfer, The Pokemon would still be 'Transferring...'
- Fix Typos, Whitespace, and Unnecessary 'RenderTransformOrigin' XAML and Adds some Extra Simplifications
- Removes Both Error and AccountSwitch Popups in exchange to display on lblAccount
- Updated Fody to 2.0.9 from 2.0.8
- Errors that require Exiting will both display on lblAccount, Will Auto …
> Many Bug Fixes & General Improvements - Ready to Merge!

- PoGo.NecroBot.Logic/Utils/Statistics.cs
Reapplies PR #1746 due to the changes in `PoGo.NecroBot.Logic/Utils/Statistics.cs` being overwritten by https://github.com/Necrobot-Private/NecroBot/commit/29c82279f5ded634b5e135383c2e7417ed7932d3#diff-5b443eea65f8ae318580c32ef320f856
#1807
> Reapply Level Up Reward Fix
