PoGo.NecroBot.Logic/Tasks/SnipeMSniperTask.cs

test server

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/WebSocketHandler/ActionCommands/LevelUpPokemonHandler.cs
PoGo.NecroBot.Logic/Event/PokemonLevelUpEvent.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Tasks/LevelUpSpecificPokemonTask.cs

add ability for websocket to manually level up pokemon

---

PoGo.NecroBot.Logic/Tasks/SnipeMSniperTask.cs

request limitation -

---

PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

revert & fix wrong commit #90

---

PoGo.NecroBot.CLI/CommandLineUtility/Arguments.cs
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/Program.cs

'NecroBot2.exe [-subpath="string"] [-jsonvalid="bool"]
[-killswitch="bool"] [-latlng="double,double"]
**OPTIONS:**
-subpath: Default sub directory path (default value: "").
-jsonvalid: Enable json validation (default value: "true").
-killswitch: Enable kill switch verification (default value: "true").
-latlng: Default start location (set in config.json by default).
**EXAMPLE:**
NecroBot2.exe -killswitch="false" -latlng="48.78523,-23.312125"

Add CommandLine Args

---

PoGo.NecroBot.CLI/Config/Translations/translation.ja-JP.json
PoGo.NecroBot.CLI/Config/Translations/translation.ja-JP2.json

JP - correct translation

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj

necrobot2.exe.config: crash bug fixed

---

PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Reverts Necrobot-Private/NecroBot#190

Revert "msniper: old and new format at the same time"

---

PoGo.NecroBot.Logic/State/VersionCheckState.cs

Show full version in command line during version check.
Fixes #262

Fixes bug #262 - Show full version in command line during version check

---

PoGo.NecroBot.Logic/Common/PokemonGradeHelper.cs

grade mistakes

---

PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs

msniper important bug fix-2

---

PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs

Bug fix - The log level was set incorrectly so info messages were being logged as errors.

Fix incorrect log level for prompt.

---

PoGo.NecroBot.CLI/BotDataSocketClient.cs

just remove a bad word 

---

PoGo.NecroBot.Logic/Model/Settings/SnipeFIlter.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs

cause bot snipe too much then out of ball, block snipe for 5 minutes

Minor fix - block autosnipe when out of ball

---

PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/MultipleBotConfig.cs
PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
PoGo.NecroBot.Logic/Service/Elevation/GoogleElevationService.cs
PoGo.NecroBot.Logic/Service/Elevation/MapQuestElevationService.cs
PoGo.NecroBot.Logic/Service/GoogleDirectionsService.cs
PoGo.NecroBot.Logic/State/Session.cs
PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
PoGo.NecroBot.Logic/Utils/ExcelConfigHelper.cs

- Allow user turn on/off bot switch by softban pokestop
- some fixed for autosnipe incase out of ball
- excel config enhancement to allow automatically add new config when code change
- fix fake softban pokestop when inventory full

Add SoftbanPokestopCount config

---

PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs

minor changes for mssvc

---

PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs

it will ready when published release

new feature is implemented

---

PoGo.NecroBot.CLI/BotDataSocketClient.cs
PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Event/EncounteredEvent.cs
PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/DataSharingConfig.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Thanks @msx752 , 
I borrow his ideal from msniper.com to put in mypogosnipers.
- the code on mypogosnipers.com has been update and support this manual snipe, this is code change require for this feature on bot code.

Manual snipe support from mypogosnipers 

---

PoGo.NecroBot.CLI/BotDataSocketClient.cs
PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Event/EncounteredEvent.cs
PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/DataSharingConfig.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/MultipleBotConfig.cs
PoGo.NecroBot.Logic/State/Session.cs
PoGo.NecroBot.Logic/State/SessionStats.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

- Add option and menu to allow select bot for at start up screen
-Separate sessiondb by each bot and store in separate folder.

Multibot enhance1

---

PoGo.NecroBot.Logic/State/Session.cs
PoGo.NecroBot.Logic/State/SessionStats.cs

Firs time use bot crash because username empty

fix issue with first time initial config - empty username cause crash

---

PoGo.NecroBot.Logic/Model/Settings/SnipeConfig.cs

default value of ActivateMSniper is TRUE

---

KillSwitch.txt

Seeing as Kill Switch has been turned on again

Update KillSwitch.txt to reflect recent turning on of KillSwitch

---

PoGo.NecroBot.CLI/WebSocketHandler/GetCommands/Helpers/PokemonListWeb.cs
PoGo.NecroBot.CLI/WebSocketHandler/GetCommands/Tasks/GetPokemonListTask.cs

Send the Candy count over websocket for viewing on GUI.

(GuiCandies) Send candy info to GUI as FamilyCandies

---

PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Exceptions/ActiveSwitchByRuleException.cs
PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/State/LoginState.cs
PoGo.NecroBot.Logic/State/Session.cs
PoGo.NecroBot.Logic/State/StateMachine.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/EggsListTask.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs
PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/TransferWeakPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

- rocket API has been update and merge to master
- remove al code call RefreshInventoryCached

Add inventory auto fresh

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/Event/PokemonEvolveEvent.cs
PoGo.NecroBot.Logic/State/LoginState.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs

fix issue : manual snipe doesn't work if not enable autosnipe.

fix manual snipe 

---

PoGo.NecroBot.Logic/Model/Settings/SnipeFIlter.cs

Allow 101 in IV for Snipe that allow exclude snipe

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Model/Settings/SnipeConfig.cs
PoGo.NecroBot.Logic/Model/Settings/SnipeFIlter.cs
PoGo.NecroBot.Logic/State/VersionCheckState.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs

Allow snipe for auto snipe candy

add candy snipe mode

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

- improves and fixes german I18N values

- german I18N

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Event/Player/BuddyUpdateEvent.cs
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Model/Settings/MultipleBotConfig.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/State/Session.cs
PoGo.NecroBot.Logic/State/StateMachine.cs
PoGo.NecroBot.Logic/Tasks/EvolveSpecificPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/SelectBuddyPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UpgradeSinglePokemonTask.cs
PoGo.Necrobot.Window/Controls/MapControl.xaml.cs
PoGo.Necrobot.Window/Controls/PokemonInventory.xaml
PoGo.Necrobot.Window/Controls/PokemonInventory.xaml.cs
PoGo.Necrobot.Window/MainClientWindow.xaml

- Allow add buddy pokemon from GUI
- Gym battle added back - need feedback
- Add max powerup button

allow add buddy from GUI

---

PoGo.NecroBot.Logic/Model/Settings/GymConfig.cs
PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs

Add config swith to enable/disable gym attack (default false)
Optimized delays after attacks to be exact we need. Number of errors in battle drastically reduced (as for now to 0)
Moved logs from screen to debug

Gym attack module optimization

---

PoGo.NecroBot.Logic/Forms/AutoUpdateForm.Designer.cs
PoGo.NecroBot.Logic/Forms/AutoUpdateForm.cs
PoGo.NecroBot.Logic/Forms/AutoUpdateForm.resx
PoGo.NecroBot.Logic/Forms/Extentions.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/State/Session.cs
PoGo.NecroBot.Logic/State/VersionCheckState.cs
PoGo.Necrobot.Window/Controls/SniperControl.xaml
PoGo.Necrobot.Window/Controls/SniperControl.xaml.cs
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/Model/AddManualSnipeCoordViewModel.cs
PoGo.Necrobot.Window/Model/SnipeListViewModel.cs
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
changelogs/v1.0.0.64.rtf
changelogs/v1.0.0.65.rtf

-- Allow auto update display release notes in update screen - should update changelogs/v1.0.0.xx.rff
-- allow manual update coords

Auto update & Manual snipes input

---

PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs

Add to rename favorite pokemon

---

PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Service/TelegramCommand/ProfileCommand.cs
PoGo.NecroBot.Logic/Service/TelegramCommand/StatusCommand.cs

Telegram /profile Command refactored
relates to Issue #556

Telegram profile

---

PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

skips already trained gym when you've trained above limit
some other minor bugfixes.

gym module

---

PoGo.NecroBot.Logic/Tasks/EvolveSpecificPokemonTask.cs
PoGo.Necrobot.Window/Model/PokemonDataViewModel.cs
PoGo.Necrobot.Window/Model/PokemonListModel.cs

The WPF GUI's pokemon inventory view is not properly updated after evolving. This is a bug fix for this.

Bug fix - WPF gui inventory not updating properly after evolve

---

PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Changed time to UTC not local in checking bonus time
Bug in gym training, after deploying pokemon was going to one more training round

Gym tunnings

---

PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
PoGo.NecroBot.Logic/Tasks/FavoritePokemonTask.cs

It'll correct these 2 things and will create new Pull Request.
Added new configuration option allows you to set the minimum CP for Auto Favorite. This option works in conjunction with setting minimum IV.

Added Minimum CP for Auto Favorite

---

PoGo.NecroBot.CLI/Program.cs

This re-enables the kill switch override, which was disabled during testing.

Re-enable kill switch override.

---

PoGo.NecroBot.Logic/State/CheckTosState.cs

First time tutorial occasionally fails to correctly complete the tutorial (selecting gender, pokemon, etc.)  This causes account to be in a stuck loading state after login.
For now I'm reverting back to the text-based first time tutorial until we figure out why it's happening with the GUI tutorial form.

Revert change to the first time tutorial for now.

---

PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Updated Rocket API to add caching for map requests. This fixes the "No Pokestops" bug that shows up when you first start up the bot. It should also improve the performance of the bot (fewer api requests).

Add caching for map requests.

---

PoGo.NecroBot.Logic/Event/Inventory/InventoryRefreshedEvent.cs
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/State/Session.cs
PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs
PoGo.Necrobot.Window/MainClientWindow.xaml.UIEvents.cs
PoGo.Necrobot.Window/Model/EggsListViewModel.cs
PoGo.Necrobot.Window/Model/PlayerInfoModel.cs
PoGo.Necrobot.Window/Model/PokemonDataViewModel.cs
PoGo.Necrobot.Window/Model/SnipeListViewModel.cs

More fixes for inventory crashes when transferring pokemon.

Bug fix/threadsafe inventory

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
PoGo.NecroBot.Logic/Utils/Statistics.cs
PoGo.Necrobot.Window/Controls/PlayerInfo.xaml
PoGo.Necrobot.Window/Model/PlayerInfoModel.cs

Fix stardust display in GUI.
Fixes bug #685

Fix bug #685 - Fix stardust not updating in GUI

---

PoGo.NecroBot.Logic/Model/Settings/ClientSettings.cs
README.md

API Update to 0.55

---

PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs

 Solved issue issue # 704

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.Logic/Model/Settings/GymConfig.cs
PoGo.NecroBot.Logic/State/GymTeamState.cs
PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs

A better dodge, some tunnings, first attempt to tune up gym trainings

Gym update

---

PoGo.NecroBot.Logic/State/GymTeamState.cs
PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs

Fix Healing Pokemon before the next fight.

Fix Healing Pokemon before the next fight.

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs

Add proper calculation of the number of evolutions possible taking into account candy received from transfers and evolves.
Bug #705

Fix bug #705 - Evolution calculations

---

PoGo.NecroBot.Logic/Tasks/HumanWalkSnipeTask.cs

Fix occasional crash related to human sniping feature due to concurrent modification of list during enumeration.

Bug fix - Human sniping crash

---

PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
PoGo.NecroBot.Logic/Tasks/SelectBuddyPokemonTask.cs

We don't want to force all users to switch their buddy to Dragonite.
Fixes #749

Change DefaultBuddyPokemon to have a default value of null

---

PoGo.NecroBot.Logic/State/SessionStats.cs

Fix occasional crash due to LiteDB 2 not being multithreaded.  LiteDB 3 supposed to be multithreaded, but for now we are using LiteDB 2 since upgrading database from 2 to 3 is not yet supported!

Fix multithreading crash due to LiteDB 2 not being thread-safe.

---

PoGo.NecroBot.Logic/State/GymTeamState.cs
PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs

Switch pokemon always results in can't start battle on next defender. Function switching pokemon is deactivated.
I tried in many ways, with extra delays, even changed data flow, same result. Switching pokemon is always working fine but always produce error on next run, so I've made some code wrapped in if blocks and added  _testSwapPokemon field in UseGymBattleTask class.
@samuraitruong please set it to true with _logTimings to have very detailed log and check by your own. Maybe you will see where i messed up.

Gym module update

---

PoGo.NecroBot.Logic/Inventory.cs

changed candy gain after evolution

changed candy gain after evolution

---

PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

This is to fix bot frequently changing destinations.
Fix #783

Bug fix - Reverts pull #741

---

PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs

Add migration for issue #781.
#781

Add migration for DefaultBuddyPokemon

---

PoGo.NecroBot.CLI/BotDataSocketClient.cs
PoGo.NecroBot.Logic/Event/SnipeEvent.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
changelogs/v1.0.0.98.rtf

allow sync snipe fail event back to server - initial

---

PoGo.NecroBot.CLI/BotDataSocketClient.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
PoGo.NecroBot.Logic/Utils/LocationUtils.cs
PoGo.Necrobot.Window/Controls/PokemonInventory.xaml

- Niantic remove PlayerUpdate api cal we just do a quick hotfix
-Disable autosnipe/manual snipe until we test it works good

disable snipe & API UpdatePlayer removed

---

PoGo.NecroBot.Logic/State/CheckTosState.cs

This change ensures that whenever we are checking the tutorial state, we always get refreshed information.
Fixes bug #822

Fix bug #822 - First time tutorial does not complete correctly.

---

PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Update cooldown of pokestop in the cache.
Also fix bug with not spinning nearby pokestops unless there are at least 2 nearby (it should spin if there is 1 nearby).

Better synchronize the pokestop cooldown. 

---

PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs

WIP, please don't merge
1. Allow fast snipe verify data

reactivate fast snipe for verify data

---

PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

temporary fix issue loop with unable to spin pokstop

temporary call get map object to resolve softban

---

PoGo.Necrobot.Window/Controls/PokemonInventory.xaml
PoGo.Necrobot.Window/Controls/PokemonInventory.xaml.cs
PoGo.Necrobot.Window/Model/PokemonDataViewModel.cs
PoGo.Necrobot.Window/Model/PokemonListModel.cs
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config

Selecting pokemon in WPF GUI was showing a blank line due to new filtering code being added.  This is a revert of those changes.
@samuraitruong The new filtering code that was merged into master is now in a feature branch: https://github.com/Necrobot-Private/NecroBot/tree/feature/wpf_gui_search_form
Please merge back when it is ready.
Fixes bug #852

Temporarily revert search form causing blank selection line in WPF GUI.

---

PoGo.NecroBot.Logic/Strategies/Walk/GoogleStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/MapzenNavigationStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/YoursNavigationStrategy.cs

Fix null reference errors with Google, Mapzen, and Yours walk strategies caused by changes for 0.57.2.

Fix bug for walk strategy null error

---

PoGo.NecroBot.Logic/Common/UITranslation.cs
PoGo.Necrobot.Window/Config/Translations/ui.pl.json
PoGo.Necrobot.Window/Controls/PokemonInventory.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml

Don't merge please. 
tasks bar sentences "pokemons {0/1}" and "items {0/1}" are still in English and some things still need it's place in translation. I might do that but I don't know which files I have to change to work good.
Where appears "close"?

Some translation + polish translation

---

PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs

back compitable

---

PoGo.NecroBot.Logic/Model/Settings/BerryUseFilter.cs
PoGo.NecroBot.Logic/Model/Settings/EvolveFilter.cs
PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
PoGo.NecroBot.Logic/Model/Settings/ItemRecycleFilter.cs
PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
PoGo.NecroBot.Logic/MultiAccountManager.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/PoGoUtils/PokemonEvolutionHelper.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
PoGo.Necrobot.Window/Converters/ItemIdToImageConverter.cs

fix loop when switch accounts manual

fix manual switch loop

---

PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs

Added reset the number of attempts to start fighting after a successful attack attempt.

Added reset the number of attempts to start fighting

---

PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Service/TelegramCommand/AccountsCommand.cs
PoGo.NecroBot.Logic/Service/TelegramCommand/ProfileCommand.cs
PoGo.NecroBot.Logic/Service/TelegramCommand/StatusCommand.cs

- Add current stardust and pokecoins to status message
- Add pokecoins to telegram profile message
- Fix Telegram accounts message 
- Fix Telegram status message

- Fix some telegram messages

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/State/LoadSaveState.cs

Fix critical issue, the lastcoord save snipe location

Lastcoord when snipe fix

---

PoGo.NecroBot.Logic/Inventory.cs

Fix candy to evolve to always look at the value in evolution branches. We should no longer be using Settings.CandyToEvolve since it is not always updated for Gen2.
If evolveTo is provided by filter then use this to select EvolutionBranch. Otherwise select the first branch which does not have an evolution item requirement.

Bug fix - Evolution candy

---

PoGo.NecroBot.Logic/Tasks/MSniperServiceTask.cs

remove debug log message

---

README.md

README: Show Screen Shots of Win GUI

---

.gitmodules

Use git extension for URL

---

PoGo.NecroBot.CLI/WebSocketHandler/GetCommands/Helpers/PokemonListWeb.cs

Send the Pokemon Level info over websocket to be used on PokeEase

send pokemon level info on websocket

---

PoGo.Necrobot.Window/Controls/MapMarkers/MapPokemonMarker.xaml

Pokémon do have Genders in Pokémon GO too
Thus Him is not r8 always

Fix Grammer

---

PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Model/Settings/EvolveFilter.cs
PoGo.NecroBot.Logic/Model/Settings/GlobalSettings.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
PoGo.NecroBot.Logic/State/CatchState.cs
PoGo.NecroBot.Logic/State/FarmState.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/HumanRandomActionTask.cs
PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/TransferWeakPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
PoGo.NecroBot.Logic/Utils/ExcelConfigHelper.cs
PoGo.Necrobot.Window/SettingsWindow.xaml.cs

Several updates to evolve logic:
1. Remove the PokemonsToEvolve setting. It is now replaced by PokemonEvolveFilter and is no longer necessary.
2. Transfers are now always performed before evolves. This maximizes evolves by transferring pokemon to get candy for evolve.
3. Transfers will check PokemonEvolveFilter and pokemon which are going to be evolved will be excluded from transfer list.
4. Add new MinCandiesBeforeEvolve to PokemonEvolveFilter. If this is greater than 0, then the bot will keep transferring to save at least this much candy before evolving.  
Example for maximizing lucky egg - According to PidgeyCalc, with 900 candies and 90 pidgeys, it would take 30 min. to evolve all 90 pidgeys.
```
"PokemonEvolveFilter": {
"Pidgey": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": …
```

Bug fix/evolutions

---

PoGo.Necrobot.Window/Controls/MapMarkers/MapPokemonMarker.xaml

Increase Button width for catching Pokemon on Map

---

PoGo.NecroBot.Logic/Model/Settings/MultipleBotConfig.cs
PoGo.NecroBot.Logic/Utils/Statistics.cs

This implements: https://github.com/Necrobot-Private/NecroBot/issues/943
Added 1 new option to MultipleBotConfig for user to add random time (RuntimeSwitchRandomTime).
Randomize has been implemented to Statistics using boolean for setting/resetting random time to make bot run for RuntimeSwitch +- RuntimeSwitchRandomTime option time.

Issue 943 implemented

---

appveyor.yml

Now it should only build master branch and pull requests which will speed up our builds.

Update appveyor build so that we don't perform 2 builds per pull request

---

PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs

Fixes a few bugs with lucky egg use:
1) If we don't have eggs don't try to use the egg.
2) If we tried to use egg and it failed, don't reset the lucky egg timer.
3) Make sure lucky egg count is up-to-date when we sent out events.
This fixes issues seen in discord related to UseItemXpBoost.

Fix bugs with lucky egg use.

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Utils/PushNotificationClient.cs
PoGo.NecroBot.Logic/packages.config
PoGo.Necrobot.Window/Model/PokemonListModel.cs
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config

Update dependencies and remove unused packages.

Clean up packages

---

PoGo.NecroBot.Logic/MultiAccountManager.cs
PoGo.NecroBot.Logic/State/LoginState.cs
PoGo.Necrobot.Window/MainClientWindow.xaml

Display the last login status for accounts in the account list.  This data is stored in the accounts database.

Show last login status for accounts.

---

PoGo.NecroBot.Logic/Model/Settings/DeviceConfig.cs
PoGo.NecroBot.Logic/MultiAccountManager.cs
PoGo.NecroBot.Logic/State/Session.cs

This fixes the device id so that it is not always random.

Add salt for device id so that the device id is not constantly changing.

---

PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

Add loot pokestop and encounter delegates, which may make it easier to integrate with other GUI's.

Add delegates from Furtif's branch.

---

KillSwitch.txt
README.md

Latest API 0.57.4

---

PoGo.NecroBot.CLI/Properties/AssemblyInfo.cs
PoGo.NecroBot.GUI/Properties/AssemblyInfo.cs
PoGo.NecroBot.Logic/Properties/AssemblyInfo.cs
PoGo.Necrobot.Window/Properties/AssemblyInfo.cs

Version Update

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

Added german translation for 2nd gen pokemon

---

PoGo.NecroBot.Logic/Interfaces/Configuration/ILogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs

FurtifFerox&FinalLocalCatchUpdate

---

PoGo.NecroBot.Logic/State/StateMachine.cs

Attempting to work around hash server error causing session invalidation.
Fixes #1234

Bug fix/session invalidation

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/State/VersionCheckState.cs

move Application.EnableVisualStyles();

Move Application.EnableVisualStyles and fix clean accounts after update

---

PoGo.NecroBot.Logic/Model/Settings/LogicSettings.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs

Count catch flee against the catch limit.
Change the limits to not be randomized.

Pokemon/Pokestop Limit Updates

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.CLI/Resources/ProgressBar.cs

fix ProgressBar

---

PoGo.NecroBot.Logic/Model/GeoLocation.cs

Bug fix for first time start up - We need to create cache dir since it doesn't exist yet.

Create cache dir for geo locations cache if it doesn't exist.

---

PoGo.NecroBot.Logic/Model/ElevationLocation.cs
PoGo.NecroBot.Logic/Model/GeoLocation.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Service/Elevation/BaseElevationService.cs
PoGo.NecroBot.Logic/Service/Elevation/ElevationService.cs
PoGo.NecroBot.Logic/Service/Elevation/GoogleElevationService.cs
PoGo.NecroBot.Logic/Service/Elevation/MapQuestElevationService.cs
PoGo.NecroBot.Logic/Service/Elevation/MapzenElevationService.cs
PoGo.NecroBot.Logic/Service/Elevation/RandomElevationService.cs
PoGo.NecroBot.Logic/packages.config
PoGo.Necrobot.Window/Model/PokemonListModel.cs

Improve performance of elevation web services by caching altitudes in local database.

When using elevation service, store altitudes in local database.

---

PoGo.NecroBot.Logic/Model/Settings/MultipleBotConfig.cs
PoGo.NecroBot.Logic/MultiAccountManager.cs
PoGo.NecroBot.Logic/Service/TelegramCommand/AccountsCommand.cs
PoGo.NecroBot.Logic/State/StateMachine.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
PoGo.NecroBot.Logic/Utils/Statistics.cs

Bug fixes for multibot changes when only single account is configured.

Fix null reference error related to startup after multibot changes.

---

PoGo.NecroBot.CLI/Program.cs

fix --help cmdline

---

PoGo.Necrobot.Window/Converters/ItemIdToImageConverter.cs

Using Pokemon GO Gen 2 item sprites

Use Pokemon GO item sprites

---

PoGo.Necrobot.Window/Model/DataContext.cs

The Pokemon Count Display was getting stuck at 241/250 when full.
This Might Fix
I haven't tested

Bug Fix: Pokemon Count Display

---

PoGo.NecroBot.Logic/State/VersionCheckState.cs

Fix download url for BinTray

---

PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs
PoGo.NecroBot.Logic/Model/Settings/TransferFilter.cs

Allow 100 IV to be set `KeepMinIvPercentage`.
Fixes #1214

Allow 100 IV to be transferred

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/LevelUpSpecificPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/PokemonListTask.cs
PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs
PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

This should improve responsiveness of the GUI and avoid potential deadlocks.

Replace usage of DelayingUtils.Delay with DelayingUtils.DelayAsync

---

PoGo.Necrobot.Window/Controls/EggsControl.xaml
PoGo.Necrobot.Window/Model/EggsListViewModel.cs

The problem is that the AddOrUpdate Event overwrites the IncubatorUpdate Event.
Please test it, its my first bugfix for NecroBot
Should fix Bug #590

Bug  Egg Display Distance Bug

---

PoGo.Necrobot.Window/Controls/EggsControl.xaml.cs
PoGo.Necrobot.Window/Controls/ItemsInventory.xaml.cs
PoGo.Necrobot.Window/Controls/MapControl.xaml.cs
PoGo.Necrobot.Window/Controls/MapMarkers/FortMarker.xaml.cs
PoGo.Necrobot.Window/Controls/MapMarkers/GymMarker.xaml.cs
PoGo.Necrobot.Window/Controls/MapMarkers/MapPokemonMarker.xaml.cs
PoGo.Necrobot.Window/Controls/PokemonInventory.xaml.cs

Async fixes in WPF GUI.  We should be using async click handlers instead of Task.Run.

Fix async usage in WPF by using async click handlers instead of Task.Run

---

PoGo.NecroBot.Logic/Inventory.cs

Works Again Bot Will Now Keep The Number You Have Set Even If It Doesnt Meet Your Other KeepMinRequirements
Close #1309 #1266

FixKeepMinDuplicatePokemon

---

PoGo.NecroBot.Logic/Model/Settings/PokemonConfig.cs

Set Range of Great ball and Ultra ball IV to (0-101)

---

PoGo.NecroBot.Logic/Model/Settings/AuthSettings.cs

Bug fixes:
Fix SSL cert error with PogoDev hash server.
Fix captcha on login error.

Update rocket API to fix ssl cert error and captcha login errors.

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.CLI/Resources/ProgressBar.cs

Update console titre on loading

---

PoGo.Necrobot.Window/Model/PokemonDataViewModel.cs

Ready to merge. 
Shiny sprites not pushed to assets as it uses a different directory in the last version

Forms Support

---

PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/Properties/Settings.Designer.cs
PoGo.Necrobot.Window/Properties/Settings.settings

This PR Adds a short and simple ability to save and reload the theme on launch
- Necrobot.Win

Adds Ability to Save Themes

---

PoGo.NecroBot.CLI/PushNotificationListener.cs
PoGo.NecroBot.CLI/SniperEventListener.cs

Make sure we don't forget to call ConfigureAwait(false) if you are awaiting a method inside of Logic library.

Add missing ConfigureAwait(false)

---

PoGo.NecroBot.Logic/State/VersionCheckState.cs

We've exceeded bintray's free open source plan, so going to switch back to GitHub for releases.

Switch back to GitHub releases.

---

PoGo.NecroBot.Logic/State/VersionCheckState.cs

Updated url for download from Github.

Updated filename for download

---

PoGo.NecroBot.Logic/Tasks/SetMoveToTargetTask.cs

Fix crash on move to target
Fixes #1461 
Fixes #1339

Fixes bug #1461 - Crash with move to target

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/packages.config
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config
README.md

MahApps.Metro - 1.4.3 > 1.5.0
AeroWizard - 2.1.9.0 > 2.1.10.0
Newtonsoft.Json.Schema - 2.0.10 > 2.0.11
Thrower (RocketAPI) - 4.1.2 > 4.1.3
PRs:
- [RocketAPI](https://google.com)

Updates Dependencies

---

PoGo.NecroBot.Logic/MultiAccountManager.cs

Sort initial account list by id

---

PoGo.NecroBot.Logic/DataDumper/Dumper.cs

Fix Excel Exporting Bug

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json

* Pokemons 100% translated
* Moves 100% translated

Update translation.fr.json 

---

NecroBot-Private for Pokemon GO.sln
PoGo.NecroBot.Logic/Common/UITranslation.cs
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/Properties/Settings.Designer.cs
PoGo.Necrobot.Window/Properties/Settings.settings

- Adds Dark Mode
- Fixes Browser Rendering Issues

Adds Dark Mode - HydraBuild

---

.gitmodules
build.bat

Features:
- Adds New Build.bat to detect and build Automatically based on VS Version

New Build.Bat to Detect VS Install and Use it's MSBuild - HydraBuild (Ready to Merge)

---

.gitmodules
NecroBot-Private for Pokemon GO.sln
PoGo.NecroBot.Logic/Common/UITranslation.cs
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/Properties/Settings.Designer.cs
PoGo.Necrobot.Window/Properties/Settings.settings

Reuploaded from Past Merge to include some fixes

Dark Mode - HydraBuild - REUPLOADED

---

build.bat

Update build.bat and nuget

---

PoGo.NecroBot.Logic/Model/Settings/DataSharingConfig.cs

fix default snipe links

---

PoGo.Necrobot.Window/Model/PokemonDataViewModel.cs

Signed-off-by: Executive Dronpes <lordhajisinbox@gmail.com>

Fix Sprites Display on Pokemon Tab Grid

---

PoGo.Necrobot.Window/MainClientWindow.xaml

Signed-off-by: Executive Dronpes <lordhajisinbox@gmail.com>

Fix Browser Naming

---

PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs

Signed-off-by: Executive Dronpes <lordhajisinbox@gmail.com>

Fix Shiny Capture Log Text

---

PoGo.NecroBot.CLI/RunWithExcelConfig.bat
PoGo.NecroBot.Logic/Model/Settings/AuthSettings.cs
PoGo.NecroBot.Logic/Model/Settings/EvolveFilter.cs
PoGo.Necrobot.Window/Properties/AssemblyInfo.cs

Signed-off-by: Executive Dronpes <lordhajisinbox@gmail.com>

Minor Fixes

---

PoGo.NecroBot.CLI/Config/Translations/translation.zh-TW.json

Add some missed key translation regarding Traditional Chinese.

Add keys translation

---

PoGo.NecroBot.CLI/FodyWeavers.xml
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/packages.config
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/Model/DataContext.cs
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config

This PR, from HydraBuild, adds Back Live Stats to Pokemon and Items Tab
Refer to Old PR for changelog or via commit history

Features/livestats - HydraBuild

---

PoGo.NecroBot.CLI/FodyWeavers.xml
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/packages.config
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config

This PR, from HydraBuild, fixes the inability to Save whether Hub is Enabled or Disabled

Bug fix/hub - HydraBuild

---

PoGo.NecroBot.CLI/packages.config
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj

ChromeDriver.2.28.0 -> not ok (in double)
ChromeDriver.2.29.0 -> current version

Delete doubled pack and update costura to 1.4.1

---

PoGo.NecroBot.CLI/Forms/AuthAPIForm.Designer.cs

Removes the old 'Cherry on Top' Key

Update AuthAPIForm.Designer.cs - Removes Old Key

---

PoGo.NecroBot.CLI/FodyWeavers.xml
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.Necrobot.Window/FodyWeavers.xml
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/Model/DataContext.cs
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
README.md

Adds HydraBuild to Necrobot
See Older PR for Changelog

Features/HydraBuild - v159/v160

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.Logic/Common/UITranslation.cs
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/Properties/Settings.Designer.cs
PoGo.Necrobot.Window/Properties/Settings.settings
README.md

Features/HydraBuild - Implements #1592 Plus Smarter Logic

---

PoGo.NecroBot.CLI/Program.cs

Implement https://github.com/Necrobot-Private/NecroBot/pull/1579 without Entire File Replace

Implements #1579

---

PoGo.NecroBot.Logic/Logging/APILogListener.cs

https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/116

Add functions for fixes player warnings

---

PoGo.NecroBot.CLI/Program.cs

Mask the ApiKey to not be logged completely

---

PoGo.NecroBot.Logic/Service/BotDataSocketClient.cs

Turn of log spam when bot data socket does not connect.

Turn of log spamming when bot data socket does not connect.

---

PoGo.NecroBot.Logic/Service/BotDataSocketClient.cs

this will help client & server site communicate better. also do not disconnect or terminate client when get connection limit message

some snipe method change to adapt with new implement on server side

---

PoGo.NecroBot.Logic/Service/AnalyticsService.cs
PoGo.NecroBot.Logic/Service/BotDataSocketClient.cs

Improve performance of analytics event handling.

Performance enhancements

---

PoGo.Necrobot.Window/Controls/SniperControl.xaml
PoGo.Necrobot.Window/Model/PokedexItemsViewModel.cs
PoGo.Necrobot.Window/PokedexWindow.xaml

Bug fix/wpf gui

---

PoGo.NecroBot.CLI/Forms/AuthAPIForm.Designer.cs
PoGo.NecroBot.CLI/Forms/StarterConfigForm.cs
PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.CLI/Properties/AssemblyInfo.cs
PoGo.NecroBot.Logic/Navigation.cs
PoGo.Necrobot.Window/Controls/MapControl.xaml.cs
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/Properties/Settings.Designer.cs
PoGo.Necrobot.Window/Properties/Settings.settings
PoGo.Necrobot.Window/SettingsWindow.xaml
PoGo.Necrobot.Window/SettingsWindow.xaml.cs
RocketBot2/Properties/AssemblyInfo.cs
RocketBot2/RocketBot2.csproj

Quick Tweaks + Map/Zoom Modes and Saving + Crash Fixes - Ready to Merge!

---

PoGo.NecroBot.Logic/Event/GetRouteEvent.cs
PoGo.NecroBot.Logic/Navigation.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Strategies/Walk/BaseWalkStrategy.cs
PoGo.NecroBot.Logic/Strategies/Walk/IWalkStrategy.cs
RocketBot2/Forms/MainForm.cs
RocketBot2/RocketBot2.csproj

This fixes a bug with Google Walk where the Google API key was used up twice as fast due to the fact that we were calling Google API's once to get a "human-like" route in Navigation.cs and then a second time in Strategies/Walk/GoogleStrategy.cs.
The `GetHumanizeRouteDelegate` that was added when we merged in RocketBot code does it's own Google Walk implementation which is not ideal.
So this pull updates the delegate to hook into the walk strategies in order to get the points that it needs to render the route.
@Furtif Please look this over.
Fixes #1628

Bug Fix - Google Walk API limit error

---

PoGo.NecroBot.CLI/Config/Translations/translation.zh-TW.json

Added Gen2 Pokemon translation regarding Traditional Chinese

---

PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs

Better handling of dotnetbrowser initialization and destruction.

Better error handling around dotnetbrower destruction.

---

PoGo.NecroBot.Logic/Model/AccountConfigContext.cs
PoGo.NecroBot.Logic/Model/ElevationConfigContext.cs
PoGo.NecroBot.Logic/Model/GeoLocationConfigContext.cs
RocketBot2/RocketBot2.csproj
RocketBot2/packages.config

Also ensure that directories exist before we create databases in them.

Add entity framework nuget packages for RocketBot.

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/packages.config
PoGo.Necrobot.Window/FodyWeavers.xml
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config
RocketBot2/RocketBot2.csproj
RocketBot2/packages.config

Consolidate Packages

---

PoGo.NecroBot.Logic/Model/AccountConfigContext.cs
PoGo.NecroBot.Logic/Model/ElevationConfigContext.cs
PoGo.NecroBot.Logic/Model/GeoLocationConfigContext.cs
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs

Self-Explanitory 👍 
Will Close and Reopen after #1641 is merged

#1641 's Improvements + Centers Tabs Fully to Ensure Aligned

---

PoGo.NecroBot.Logic/Model/GeoLocation.cs

When you have hit the Google API limits, this fix prevents the bot from continually trying to get locations.  Now it will blacklist the service and retry in 1 hour.

Add blacklist for geolocation cache.

---

PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs

This is a re-layout of the tabs to the bottom of the window. I think it makes it a little cleaner.  On some of my low resolution screens also the vertical tabs would cut off the last tab (eggs), so this is a bit better for low resolution screens.

Win GUI Reworked Layout - Bottom Tabs - Request for Feedback

---

PoGo.NecroBot.Logic/MultiAccountManager.cs
PoGo.NecroBot.Logic/State/LoginState.cs
PoGo.NecroBot.Logic/State/SessionStats.cs

Bug fix/sqlite

---

PoGo.Necrobot.Window/MainClientWindow.xaml.UIEvents.cs
PoGo.Necrobot.Window/Model/DataContext.cs

The WPF egg count is now correctly displaying eggs in incubators out of total number of eggs.

Fix egg count to show eggs in incubators and total eggs.

---

RocketBot2/Properties/AssemblyInfo.cs

v2.9.2.0 (RocketBot2)

---

PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs

Layout Fixes & Remove Tab Hover Color Change to prevent Color Invisibility

---

PoGo.NecroBot.Logic/Forms/AutoUpdateForm.cs

Fix Typos in AutoUpdateForm

---

PoGo.NecroBot.CLI/Properties/AssemblyInfo.cs

 fix utf8 booms tripled 

---

RocketBot2/Properties/AssemblyInfo.cs

Add new cipher encryption. Credits to Xelwon of Pokemaster Bot
Refactoring - Move listeners from CLI to logic.
Fix gym battle to properly move on if gym is unattackable.
Add human walking event delegate.
Updates TinyIoC Script
[release](https://github.com/TheUnnamedOrganisation/RocketBot/releases/tag/v2.9.2.2)

v2.9.2.2 Current Build (RocketBot2)

---

RocketBot2/Config/Translations/translation.zh-TW.json
RocketBot2/Forms/MainForm.cs

Rebase all other submodules

---

PoGo.Necrobot.Window/MainClientWindow.xaml.cs

Fix invalid color

---

RocketBot2/Forms/MainForm.cs
RocketBot2/Forms/MainForm.designer.cs
RocketBot2/Forms/SettingForm.Designer.cs
RocketBot2/Forms/SettingForm.cs
RocketBot2/Models/GMapMarkerPokestops.cs
RocketBot2/Models/GMapMarkerTrainer.cs
RocketBot2/Properties/AssemblyInfo.cs

Kills the application and more (RocketBot2)

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/packages.config
PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/Properties/Settings.Designer.cs
PoGo.Necrobot.Window/Properties/Settings.settings
PoGo.Necrobot.Window/packages.config
RocketBot2/RocketBot2.csproj
RocketBot2/packages.config

- Microsoft.Extensions.XXX: 1.1.0/1.1.1 > 1.1.1/1.1.2
- Fody: 2.0.7 > 2.0.8
- System.Diagnostics.DiagnosticSource: 4.3.0 > 4.3.1
- System.Net.Http: 4.3.1 > 4.3.2
- CloudFlareUtilities: 0.2.0-Alpha > 0.4.0-Alpha
#1700 - Incorporated this Plus Major Optimizations

Tweaks, Fixes, and Enhancements

---

PoGo.Necrobot.Window/MainClientWindow.xaml.cs
RocketBot2/Config/Translations/translation.zh-TW.json
RocketBot2/Properties/AssemblyInfo.cs

fix MainClientWindow ToUnixTime missing using

---

PoGo.NecroBot.CLI/Program.cs
RocketBot2/Forms/MainForm.cs

Updated PokeHash Endpoint to api/v133_1/hash

Updated PokeHash Endpoint

---

PoGo.Necrobot.Window/Controls/MapMarkers/MapPokemonMarker.xaml

Replace Random Pokemon Image for Actual Placeholder in MapPokemonMarker

---

PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/packages.config

Updates Newtonsoft.Json.Schema from 2.0.11 to 2.0.12

---

RocketBot2/Forms/MainForm.cs
RocketBot2/Properties/AssemblyInfo.cs

https://github.com/TheUnnamedOrganisation/RocketBot/commit/3de9aff5d5aa891c329bc7f6dcf1f0a661035c5e

RocketBot2 release v2.10.1.2 (current)

---

PoGo.NecroBot.CLI/FodyWeavers.xml
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.Necrobot.Window/FodyWeavers.xml
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config
RocketBot2/RocketBot2.csproj
RocketBot2/packages.config

Update Costura.Fody to v1.5.0

---

PoGo.NecroBot.Logic/Forms/AutoUpdateForm.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/packages.config

Updated Method (Needs Github Formatting for Auto Updating .md File) - features/ImproveAutoUpdate

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Utils/Statistics.cs

Fix to properly allow collection of level up rewards when `SkipCollectingLevelUpRewards` is `false`
#1540

Fix collecting levelup rewards.

---

PoGo.NecroBot.CLI/Forms/InfoForm.cs
PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Forms/AutoUpdateForm.Designer.cs
PoGo.NecroBot.Logic/Forms/AutoUpdateForm.cs
PoGo.NecroBot.Logic/State/VersionCheckState.cs

Formatting Tweaks

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config

Updates Fody to 2.0.10 (Necrobot, view associated PR for RocketBot)

---

PoGo.Necrobot.Window/MainClientWindow.xaml
PoGo.Necrobot.Window/MainClientWindow.xaml.cs

Layout Fixes and Display Version in Window Title

---

PoGo.NecroBot.Logic/Model/BotAccount.cs
PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
PoGo.NecroBot.Logic/MultiAccountManager.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/State/SessionStats.cs
PoGo.NecroBot.Logic/packages.config

Remove old LiteDB code which is no longer in use.

Remove old LiteDB code which is no longer in use.

---

PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseLuckyEggConstantlyTask.cs
PoGo.NecroBot.Logic/Tasks/UseLuckyEggTask.cs

Fixes bugs with lucky egg.
Fixes #1488

Clean up lucky egg logic to always check expiration.

---

PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
PoGo.Necrobot.Window/MainClientWindow.xaml.UIEvents.cs

https://github.com/Necrobot-Private/NecroBot/pull/1762
https://github.com/TheWizard1328/NecroBot/pull/3

Suite of the pull request (#1762) sync

---

PoGo.Necrobot.Window/Controls/PlayerInfo.xaml

Layout and Indent Fixes for PlayerInfo

---

Gemfile
KillSwitch.txt
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/packages.config
PoGo.Necrobot.Window/Controls/PlayerInfo.xaml
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj
PoGo.Necrobot.Window/packages.config
RocketBot2/RocketBot2.csproj
RocketBot2/packages.config
build.bat

Dependencies Updated:
Costura.Fody: v1.5.1 to v1.6.1
MarkDig: v0.11 to v0.12.1
Newtonsoft.Json.Schema: v2.0.12 to v2.0.13

Update Dependencies and Adjustments

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json
PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/MultiAccountManager.cs
PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
PoGo.Necrobot.Window/Controls/PlayerInfo.xaml
RocketBot2/Config/Translations/translation.fr.json
RocketBot2/Forms/MainForm.cs

	fix multiaccount methodes

---

KillSwitch.txt
README.md

Should Be Good To GO Only Changes For Update Was EndPoint Via Eggy

Latest API Update

---

RocketBot2/Forms/InfoForm.Designer.cs
RocketBot2/Forms/InfoForm.resx
RocketBot2/Forms/MainForm.designer.cs
RocketBot2/Properties/AssemblyInfo.cs

Release v2.10.3.5 (RocketBot2)

---

PoGo.NecroBot.Logic/Model/Settings/AuthConfig.cs
PoGo.NecroBot.Logic/Model/Settings/ClientSettings.cs
PoGo.NecroBot.Logic/Model/Settings/UpdateConfig.cs
PoGo.NecroBot.Logic/State/Session.cs
RocketBot2/Properties/AssemblyInfo.cs

This updating refers to PR https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/134
Select account to exit if flagged:
"Bots": [
{
"AuthType": "ptc",
"Username": "XXXXXXXXX",
"Password": "YYYYYYYYYY",
"AutoExitBotIfAccountFlagged": true or false
}
],

Auto Exit Bot If Account is Flagged

---

RocketBot2/Properties/AssemblyInfo.cs

Update LoginUserAgent
Fix Unexpected response from Pokemon SSO OAuth Login Url: Status code NotFound
This PR refers to  https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/135

Release v2.10.3.7 (RocketBot2)

---

PoGo.Necrobot.Window/MainClientWindow.xaml.cs

For uses GUI dowload artifact  into:
https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1797-fqjldwjv/artifacts
or wait new release.

Fixes bug v1.0.0.178 Exception caught, writing LogBuffer

---

PoGo.NecroBot.Logic/Tasks/BaseTransferPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
PoGo.Necrobot.Window/MainClientWindow.xaml.cs
RocketBot2/Forms/MainForm.cs
RocketBot2/Properties/AssemblyInfo.cs

Fixes Error: System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet. (GYMS)

Release v2.10.3.8 (RocketBot2) 

---

PoGo.Necrobot.Window/Controls/PlayerInfo.xaml
PoGo.Necrobot.Window/Controls/PlayerInfo.xaml.cs
PoGo.Necrobot.Window/Model/PlayerInfoModel.cs
RocketBot2/Forms/MainForm.cs
RocketBot2/Forms/MainForm.designer.cs
RocketBot2/Properties/AssemblyInfo.cs
RocketBot2/Resources/ItemIdDB.Designer.cs
RocketBot2/Resources/ItemIdDB.resx
RocketBot2/RocketBot2.csproj

* ItemLegendaryRaidTicket
* Delete GetPokeCoin
* Rebase asset modules
* RocketBot release 2.11.0.6

add golden razz berrie and premierball ids

---

PoGo.NecroBot.Logic/Service/ConsoleEventListener.cs
PoGo.NecroBot.Logic/State/StateMachine.cs
PoGo.NecroBot.Logic/Utils/Statistics.cs

* Translation Egg hatch repair
* Pushbullet Trainer update
* Grammer rewording
* Fix pointer submodule feroxrev - GetInbox Every Request #1855

Pushbullet update & Translation - Fix pointer submodule feroxrev

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json
PoGo.NecroBot.Logic/Model/Settings/ItemRecycleConfig.cs
PoGo.NecroBot.Logic/Service/ConsoleEventListener.cs
PoGo.NecroBot.Logic/Service/TelegramService.cs
PoGo.NecroBot.Logic/Service/TelegramUtils.cs
RocketBot2/Config/Translations/translation.fr.json
RocketBot2/Properties/AssemblyInfo.cs

change pos and ordre missed in lasted pr

Fixe some bugs

---

KillSwitch.txt

Killswitch Hotfix
